/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MESSAGES_ROBOCUP_SSL_DETECTION_PB_H_INCLUDED
#define PB_MESSAGES_ROBOCUP_SSL_DETECTION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SSL_DetectionBall {
    float confidence;
    bool has_area;
    uint32_t area;
    float x;
    float y;
    bool has_z;
    float z;
    float pixel_x;
    float pixel_y;
} SSL_DetectionBall;

typedef struct _SSL_DetectionRobot {
    float confidence;
    bool has_robot_id;
    uint32_t robot_id;
    float x;
    float y;
    bool has_orientation;
    float orientation;
    float pixel_x;
    float pixel_y;
    bool has_height;
    float height;
} SSL_DetectionRobot;

typedef struct _SSL_DetectionFrame {
    uint32_t frame_number;
    double t_capture;
    double t_sent;
    uint32_t camera_id;
    pb_size_t balls_count;
    SSL_DetectionBall balls[10];
    pb_size_t robots_yellow_count;
    SSL_DetectionRobot robots_yellow[12];
    pb_size_t robots_blue_count;
    SSL_DetectionRobot robots_blue[12];
    bool has_t_capture_camera;
    double t_capture_camera;
} SSL_DetectionFrame;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SSL_DetectionBall_init_default           {0, false, 0, 0, 0, false, 0, 0, 0}
#define SSL_DetectionRobot_init_default          {0, false, 0, 0, 0, false, 0, 0, 0, false, 0}
#define SSL_DetectionFrame_init_default          {0, 0, 0, 0, 0, {SSL_DetectionBall_init_default, SSL_DetectionBall_init_default, SSL_DetectionBall_init_default, SSL_DetectionBall_init_default, SSL_DetectionBall_init_default, SSL_DetectionBall_init_default, SSL_DetectionBall_init_default, SSL_DetectionBall_init_default, SSL_DetectionBall_init_default, SSL_DetectionBall_init_default}, 0, {SSL_DetectionRobot_init_default, SSL_DetectionRobot_init_default, SSL_DetectionRobot_init_default, SSL_DetectionRobot_init_default, SSL_DetectionRobot_init_default, SSL_DetectionRobot_init_default, SSL_DetectionRobot_init_default, SSL_DetectionRobot_init_default, SSL_DetectionRobot_init_default, SSL_DetectionRobot_init_default, SSL_DetectionRobot_init_default, SSL_DetectionRobot_init_default}, 0, {SSL_DetectionRobot_init_default, SSL_DetectionRobot_init_default, SSL_DetectionRobot_init_default, SSL_DetectionRobot_init_default, SSL_DetectionRobot_init_default, SSL_DetectionRobot_init_default, SSL_DetectionRobot_init_default, SSL_DetectionRobot_init_default, SSL_DetectionRobot_init_default, SSL_DetectionRobot_init_default, SSL_DetectionRobot_init_default, SSL_DetectionRobot_init_default}, false, 0}
#define SSL_DetectionBall_init_zero              {0, false, 0, 0, 0, false, 0, 0, 0}
#define SSL_DetectionRobot_init_zero             {0, false, 0, 0, 0, false, 0, 0, 0, false, 0}
#define SSL_DetectionFrame_init_zero             {0, 0, 0, 0, 0, {SSL_DetectionBall_init_zero, SSL_DetectionBall_init_zero, SSL_DetectionBall_init_zero, SSL_DetectionBall_init_zero, SSL_DetectionBall_init_zero, SSL_DetectionBall_init_zero, SSL_DetectionBall_init_zero, SSL_DetectionBall_init_zero, SSL_DetectionBall_init_zero, SSL_DetectionBall_init_zero}, 0, {SSL_DetectionRobot_init_zero, SSL_DetectionRobot_init_zero, SSL_DetectionRobot_init_zero, SSL_DetectionRobot_init_zero, SSL_DetectionRobot_init_zero, SSL_DetectionRobot_init_zero, SSL_DetectionRobot_init_zero, SSL_DetectionRobot_init_zero, SSL_DetectionRobot_init_zero, SSL_DetectionRobot_init_zero, SSL_DetectionRobot_init_zero, SSL_DetectionRobot_init_zero}, 0, {SSL_DetectionRobot_init_zero, SSL_DetectionRobot_init_zero, SSL_DetectionRobot_init_zero, SSL_DetectionRobot_init_zero, SSL_DetectionRobot_init_zero, SSL_DetectionRobot_init_zero, SSL_DetectionRobot_init_zero, SSL_DetectionRobot_init_zero, SSL_DetectionRobot_init_zero, SSL_DetectionRobot_init_zero, SSL_DetectionRobot_init_zero, SSL_DetectionRobot_init_zero}, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SSL_DetectionBall_confidence_tag         1
#define SSL_DetectionBall_area_tag               2
#define SSL_DetectionBall_x_tag                  3
#define SSL_DetectionBall_y_tag                  4
#define SSL_DetectionBall_z_tag                  5
#define SSL_DetectionBall_pixel_x_tag            6
#define SSL_DetectionBall_pixel_y_tag            7
#define SSL_DetectionRobot_confidence_tag        1
#define SSL_DetectionRobot_robot_id_tag          2
#define SSL_DetectionRobot_x_tag                 3
#define SSL_DetectionRobot_y_tag                 4
#define SSL_DetectionRobot_orientation_tag       5
#define SSL_DetectionRobot_pixel_x_tag           6
#define SSL_DetectionRobot_pixel_y_tag           7
#define SSL_DetectionRobot_height_tag            8
#define SSL_DetectionFrame_frame_number_tag      1
#define SSL_DetectionFrame_t_capture_tag         2
#define SSL_DetectionFrame_t_sent_tag            3
#define SSL_DetectionFrame_camera_id_tag         4
#define SSL_DetectionFrame_balls_tag             5
#define SSL_DetectionFrame_robots_yellow_tag     6
#define SSL_DetectionFrame_robots_blue_tag       7
#define SSL_DetectionFrame_t_capture_camera_tag  8

/* Struct field encoding specification for nanopb */
#define SSL_DetectionBall_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    confidence,        1) \
X(a, STATIC,   OPTIONAL, UINT32,   area,              2) \
X(a, STATIC,   REQUIRED, FLOAT,    x,                 3) \
X(a, STATIC,   REQUIRED, FLOAT,    y,                 4) \
X(a, STATIC,   OPTIONAL, FLOAT,    z,                 5) \
X(a, STATIC,   REQUIRED, FLOAT,    pixel_x,           6) \
X(a, STATIC,   REQUIRED, FLOAT,    pixel_y,           7)
#define SSL_DetectionBall_CALLBACK NULL
#define SSL_DetectionBall_DEFAULT NULL

#define SSL_DetectionRobot_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    confidence,        1) \
X(a, STATIC,   OPTIONAL, UINT32,   robot_id,          2) \
X(a, STATIC,   REQUIRED, FLOAT,    x,                 3) \
X(a, STATIC,   REQUIRED, FLOAT,    y,                 4) \
X(a, STATIC,   OPTIONAL, FLOAT,    orientation,       5) \
X(a, STATIC,   REQUIRED, FLOAT,    pixel_x,           6) \
X(a, STATIC,   REQUIRED, FLOAT,    pixel_y,           7) \
X(a, STATIC,   OPTIONAL, FLOAT,    height,            8)
#define SSL_DetectionRobot_CALLBACK NULL
#define SSL_DetectionRobot_DEFAULT NULL

#define SSL_DetectionFrame_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   frame_number,      1) \
X(a, STATIC,   REQUIRED, DOUBLE,   t_capture,         2) \
X(a, STATIC,   REQUIRED, DOUBLE,   t_sent,            3) \
X(a, STATIC,   REQUIRED, UINT32,   camera_id,         4) \
X(a, STATIC,   REPEATED, MESSAGE,  balls,             5) \
X(a, STATIC,   REPEATED, MESSAGE,  robots_yellow,     6) \
X(a, STATIC,   REPEATED, MESSAGE,  robots_blue,       7) \
X(a, STATIC,   OPTIONAL, DOUBLE,   t_capture_camera,   8)
#define SSL_DetectionFrame_CALLBACK NULL
#define SSL_DetectionFrame_DEFAULT NULL
#define SSL_DetectionFrame_balls_MSGTYPE SSL_DetectionBall
#define SSL_DetectionFrame_robots_yellow_MSGTYPE SSL_DetectionRobot
#define SSL_DetectionFrame_robots_blue_MSGTYPE SSL_DetectionRobot

extern const pb_msgdesc_t SSL_DetectionBall_msg;
extern const pb_msgdesc_t SSL_DetectionRobot_msg;
extern const pb_msgdesc_t SSL_DetectionFrame_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SSL_DetectionBall_fields &SSL_DetectionBall_msg
#define SSL_DetectionRobot_fields &SSL_DetectionRobot_msg
#define SSL_DetectionFrame_fields &SSL_DetectionFrame_msg

/* Maximum encoded size of messages (where known) */
#define MESSAGES_ROBOCUP_SSL_DETECTION_PB_H_MAX_SIZE SSL_DetectionFrame_size
#define SSL_DetectionBall_size                   36
#define SSL_DetectionFrame_size                  1451
#define SSL_DetectionRobot_size                  41

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
