/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "messages_robocup_ssl_geometry.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Vector2f, Vector2f, AUTO)


PB_BIND(SSL_FieldLineSegment, SSL_FieldLineSegment, AUTO)


PB_BIND(SSL_FieldCircularArc, SSL_FieldCircularArc, AUTO)


PB_BIND(SSL_GeometryFieldSize, SSL_GeometryFieldSize, AUTO)


PB_BIND(SSL_GeometryCameraCalibration, SSL_GeometryCameraCalibration, AUTO)


PB_BIND(SSL_BallModelStraightTwoPhase, SSL_BallModelStraightTwoPhase, AUTO)


PB_BIND(SSL_BallModelChipFixedLoss, SSL_BallModelChipFixedLoss, AUTO)


PB_BIND(SSL_GeometryModels, SSL_GeometryModels, AUTO)


PB_BIND(SSL_GeometryData, SSL_GeometryData, AUTO)





#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

